apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
        - name: server
          image: aahaavis/server:latest
          env:
          - name: PORT
            value: "\x38\x30\x38\x30"
